/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [96.56KB] > C:\Users\Angus\Downloads\ubc_badge_test2 (1)\scene-transformed.glb [23.56KB] (76%)
Author: Alicjahf (https://sketchfab.com/Alicjahf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ubc-badge-test2-44756d95a7e84debb6b6b4d75ba3cd79
Title: UBC_Badge_Test2
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/img/badge3-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="pasted__pasted__polySurface4" position={[0.002, 0.007, 0.001]} rotation={[-0.058, 0.003, 0.007]} scale={0.01}>
          <group name="polySurface15" position={[-0.47, 1.011, 0.088]} rotation={[0.065, 0, 0]} />
        </group>
        <mesh name="badge_lambert7_0" geometry={nodes.badge_lambert7_0.geometry} material={materials.lambert7} position={[0, 0.005, 0]} scale={[0.028, 0.039, 0.002]} />
        <mesh name="pCube1_lambert6_0" geometry={nodes.pCube1_lambert6_0.geometry} material={materials.lambert6} position={[0, -0.007, 0]} scale={[0.013, 0.009, 0.002]} />
        <mesh name="group3_pasted__group_pasted__pasted__pCube5_lambert5_0" geometry={nodes.group3_pasted__group_pasted__pasted__pCube5_lambert5_0.geometry} material={materials.lambert5} scale={[0.012, 0.01, 0.01]} />
      </group>
    </group>
  )
}

useGLTF.preload('/img/badge3-transformed.glb')
