/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [92.8KB] > C:\Users\Angus\Downloads\ubc_badge\scene-transformed.glb [23.83KB] (74%)
Author: Alicjahf (https://sketchfab.com/Alicjahf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ubc-badge-0beacd3923754761a3a321d89b050258
Title: UBC_badge
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/img/ubc-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="pasted__pasted__polySurface4" position={[0.002, 0.007, 0.001]} rotation={[-0.058, 0.003, 0.007]} scale={0.01}>
          <group name="polySurface15" position={[-0.47, 1.011, 0.088]} rotation={[0.065, 0, 0]} />
        </group>
        <mesh name="badge_lambert7_0" geometry={nodes.badge_lambert7_0.geometry} material={materials.lambert7} position={[0, 0.005, 0]} scale={[0.028, 0.039, 0.002]} />
        <mesh name="pCube1_lambert6_0" geometry={nodes.pCube1_lambert6_0.geometry} material={materials.lambert6} position={[0, -0.006, 0.001]} scale={[0.013, 0.009, 0.002]} />
        <mesh name="pasted__pCube7_lambert1_0" geometry={nodes.pasted__pCube7_lambert1_0.geometry} material={materials.lambert1} position={[-0.005, 0.015, 0.001]} rotation={[0, 0, -2.298]} scale={[0.001, 0.002, 0]} />
        <mesh name="polySurface12_lambert5_0" geometry={nodes.polySurface12_lambert5_0.geometry} material={materials.lambert5} position={[-0.012, 0.011, 0.002]} rotation={[Math.PI, 0, -1.567]} scale={[0.01, 0.017, 0.01]} />
      </group>
    </group>
  )
}

useGLTF.preload('/ubc-transformed.glb')
